export const data = [
  {
    typeId: "Cedula de ciudadania",
    numberId: 6703827915,
    name: "Reuben",
    lastName: "Brekke",
    age: 73,
    email: "Emie_Bailey74@example.com",
    phoneNumber: "1234567890",
    liquidation: [
      {
        month: "Enero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "false",
      },
      {
        month: "Febrero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "true",
        statusParking: "false",
      },
      {
        month: "Marzo",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "true",
        statusParking: "false",
      },
    ],
    birthdayDate: "1951-09-11",
  },
  {
    typeId: "Cedula de ciudadania",
    numberId: 1567347866,
    name: "Jaclyn",
    lastName: "Keeling",
    age: 39,
    email: "Horace_Heathcote58@example.com",
    phoneNumber: "1234567890",
    liquidation: [
      {
        month: "Enero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
      {
        month: "Febrero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
      {
        month: "Marzo",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "false",
      },
    ],
    birthdayDate: "1985-04-12",
  },
  {
    typeId: "Cedula de ciudadania",
    numberId: 1843321811,
    name: "Lonny",
    lastName: "Murazik",
    age: 52,
    email: "Bernita0@gmail.com",
    phoneNumber: "1234567890",
    liquidation: [
      {
        month: "Enero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "true",
        statusParking: "true",
      },
      {
        month: "Febrero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "false",
      },
      {
        month: "Marzo",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "false",
      },
    ],
    birthdayDate: "1972-07-07",
  },
  {
    typeId: "Cedula de ciudadania",
    numberId: 4402634220,
    name: "Darlene",
    lastName: "Windler",
    age: 49,
    email: "Lloyd.Hoeger61@example.com",
    phoneNumber: "1234567890",
    liquidation: [
      {
        month: "Enero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
      {
        month: "Febrero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
      {
        month: "Marzo",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
    ],
    birthdayDate: "1975-12-03",
  },
  {
    typeId: "Cedula de ciudadania",
    numberId: 5654121829,
    name: "Dennis",
    lastName: "Schneider",
    age: 24,
    email: "Angelina20@example.com",
    phoneNumber: "1234567890",
    liquidation: [
      {
        month: "Enero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "false",
      },
      {
        month: "Febrero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "false",
      },
      {
        month: "Marzo",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "true",
        statusParking: "false",
      },
    ],
    birthdayDate: "2000-06-06",
  },
  {
    typeId: "Cedula de ciudadania",
    numberId: 2652893797,
    name: "Ansel",
    lastName: "Denesik",
    age: 55,
    email: "Magdalen.Treutel@example.com",
    phoneNumber: "1234567890",
    liquidation: [
      {
        month: "Enero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "true",
        statusParking: "true",
      },
      {
        month: "Febrero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
      {
        month: "Marzo",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
    ],
    birthdayDate: "1969-11-10",
  },
  {
    typeId: "Cedula de ciudadania",
    numberId: 9150797416,
    name: "Ceasar",
    lastName: "Johns",
    age: 55,
    email: "Elsa21@gmail.com",
    phoneNumber: "1234567890",
    liquidation: [
      {
        month: "Enero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
      {
        month: "Febrero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "true",
        statusParking: "true",
      },
      {
        month: "Marzo",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "true",
        statusParking: "true",
      },
    ],
    birthdayDate: "1969-02-25",
  },
  {
    typeId: "Cedula de extranjeria",
    numberId: 6788804848,
    name: "Lizzie",
    lastName: "Walsh",
    age: 55,
    email: "Deondre_Fisher4@example.com",
    phoneNumber: "1234567890",
    liquidation: [
      {
        month: "Enero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "false",
      },
      {
        month: "Febrero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
      {
        month: "Marzo",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
    ],
    birthdayDate: "1969-09-25",
  },
  {
    typeId: "Tarjeta de identidad",
    numberId: 7431438669,
    name: "Nelle",
    lastName: "Heaney",
    age: 58,
    email: "Mable78@gmail.com",
    phoneNumber: "1234567890",
    liquidation: [
      {
        month: "Enero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "true",
        statusParking: "true",
      },
      {
        month: "Febrero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "true",
        statusParking: "false",
      },
      {
        month: "Marzo",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
    ],
    birthdayDate: "1966-03-09",
  },
  {
    typeId: "Cedula de ciudadania",
    numberId: 6423661310,
    name: "Mara",
    lastName: "Hyatt",
    age: 40,
    email: "Garrick.Koelpin@example.com",
    phoneNumber: "1234567890",
    liquidation: [
      {
        month: "Enero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "true",
        statusParking: "false",
      },
      {
        month: "Febrero",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "true",
      },
      {
        month: "Marzo",
        administration: 1000000,
        parking: 200000,
        statusAdmin: "false",
        statusParking: "false",
      },
    ],
    birthdayDate: "1984-10-16",
  },
];
